# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-18 10:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=50)),
                ('workingunder', models.CharField(max_length=40)),
                ('searchingon', models.CharField(max_length=500)),
            ],
        ),
    ]
