# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-16 12:39
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_auto_20170416_1229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsfield',
            name='date_of_addition',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 16, 12, 39, 0, 238911)),
        ),
    ]
