# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-18 10:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=100)),
                ('institute', models.CharField(max_length=100)),
                ('interests', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, max_length=250)),
                ('lnk', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Login_Faculty',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('usrname', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('passcode', models.CharField(max_length=50)),
            ],
        ),
    ]
